name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Vite React App
        run: npm run build

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x "node_modules/*" ".git/*"

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'almazstore'                      # <- Your Beanstalk app name
          environment_name: 'almazstore-env'                 # <- Your Beanstalk environment name
          version_label: v-${{ github.run_number }}        # Unique version
          region: us-west-2                                # Change to your AWS region
          deployment_package: deploy.zip
